### ISSUE TITLE
 Can't open device /sys/class/gpio/gpio35 

### ISSUE THREAD

**Issue by miky2k** [rastersoft/gsl1680#2]
Hi,
i use mainline kernel , your driver work like charm but give me an error message above.

I export PB3  as gp35 ( B-1*32+3)
root@tablet0:/# ls /sys/class/gpio/
export  gpio35  gpiochip0  unexport
root@tablet0:# 

and launch 
./gslx680 -res 800x480 -invert_x -gpio /sys/class/gpio/gpio35  /dev/i2c-1 gsl1680_7inch_800x480.fw
touchpad work ok, but semm that gpio syntax is not correct (i didn't found your syntax in mainline kernel). 

Does your driver support interrupt (i don't know if give better performance)?

**Comment by rastersoft** [comment]
The driver doesn't support interrupts.

Exactly what error message gives it?

**Comment by miky2k** [comment]
Sorry , the message is "Can't open device /sys/class/gpio/gpio35".
I think it's syntax related but i don't know how to specitify correct path.

**Comment by rastersoft** [comment]
Maybe is a permissions problem... Have you tried to launch it as root?

**Comment by miky2k** [comment]
Ok the correct syntax is 
/sys/class/gpio/gpio35/value  * PB3 *\

Can you add to documentation ? 
I suppose you should add it as mainline kernel gpio syntax.

**Comment by rastersoft** [comment]
It seems that each system has its own syntax... Mine is /sys/devices/virtual/misc/sun4i-gpio/pin/pb3
