### ISSUE TITLE
gslx680 (D1E0DP2755C) give error in I2C

### ISSUE THREAD

**Issue by miky2k** [rastersoft/gsl1680#4]
I try your driver on a different tablet(on the first work ok) but give me this error:
mv64xxx_i2c_fsm: Ctlr Error -- state: 0x6, status: 0x0, addr: 0x40, flags: 0x0

```
buf[0]=0x88;
gsl_ts_write(client, GSL_STATUS_REG, buf, 1);
usleep(10000);
```

if i add 
ret = gsl_ts_write(client, GSL_STATUS_REG, buf, 1);
i obtain ret=-1 so error is writing GSL_STATUS_REG (maybe a nack or clock stretck ?)

how can i debug it?
may be a different flavour of gsl1680?

**Comment by rastersoft** [comment]
Wow... No idea, sorry...

Are you sure that chip is a gsl1680?

Maybe it is in another bus...

**Comment by miky2k** [comment]
Ok, gslx680 is not very 100Khz friendly , you MUST check before every transaction that bus is set to 400Khz if other drivers change it.
Set bus to 400Khz solve my problem.

Documentation:
from mainline kernel driver sun8i-reference-design-tablet.dtsi
```
&i2c0 {
	/*
	 * The gsl1680 is rated at 400KHz and it will not work reliable at
	 * 100KHz, this has been confirmed on multiple different q8 tablets.
	 * The gsl1680 is the only device on this bus.
	 */
	clock-frequency = <400000>;

	touchscreen: touchscreen@0 {
		interrupt-parent = <&pio>;
		interrupts = <1 5 IRQ_TYPE_EDGE_FALLING>; /* PB5 */
		pinctrl-names = "default";
		pinctrl-0 = <&ts_power_pin>;
		power-gpios = <&pio 7 1 GPIO_ACTIVE_HIGH>; /* PH1 */
		/* Tablet dts must provide reg and compatible */
		status = "disabled";
	};
};

```

**Comment by rastersoft** [comment]
It seems that it is not possible to change the speed of the I2C bus from userspace, so I will close this.
