### ISSUE TITLE
[Feature request] Add support for swapping x/y

### ISSUE THREAD

**Issue by swiftgeek** [rastersoft/gsl1680#5]
Support for swapping X/Y axis, silead module already implements that
https://www.kernel.org/doc/Documentation/devicetree/bindings/input/touchscreen/silead_gsl1680.txt

Example device that requires this:
http://commonemitter.blogspot.com/2016/01/manta-mid721qc.html ( https://linux-sunxi.org/AL-AX3-Q8 )

**Comment by rastersoft** [comment]
It already supports that. Just edit the "gslx680.service" file, add the parameters -invert_x and/or -invert_y, and reinstall (or edit the "gslx680.service" file at the final location).

**Comment by swiftgeek** [comment]
swapping (rotating by 90°) != inverting (rotating by 180°)

**Comment by rastersoft** [comment]
Then you should use "rotate axis" :P

**Comment by swiftgeek** [comment]
If we have just rotate field we could end up with situation where both real axis are moving pointer on the same virtual axis xD

Linux kernel already documents swap and invert for all drivers:
https://www.kernel.org/doc/Documentation/devicetree/bindings/input/touchscreen/touchscreen.txt

**Comment by rastersoft** [comment]
Ok, done. Try it please.
